### ISSUE TITLE
FastAPI Integration: optional flag not working

### ISSUE THREAD

**Issue by mfruhner** [fief-dev/fief-python#7]
## Describe the bug

I tried out the `optional` flag on the FastAPI client, but it does not seem to do anything.
No matter if the flag is set to True or False, I always get a 401 Response.

## To Reproduce

```python
@router.get("/test")
def test(
    token_info: FiefAccessTokenInfo = Depends(auth.authenticated(optional=True))
):
    print(token_info)
    return Response()
```

## Expected behavior

I receive a 200 Response and None is printed

## Configuration

* Python version: 3.11
* Fief client version: 0.14.6

* Fief Cloud or self-hosted: Cloud

**Comment by frankie567** [comment]
After checking, it seems that I forgot something important in the documentation example. The `auto_error` flag on the scheme must be set to `False` for this to work. Otherwise, the scheme will automatically raise a 401 and never run the Fief client logic. So you should have something like this in your setup:

```py
scheme = OAuth2AuthorizationCodeBearer(  
    "https://example.fief.dev/authorize",  
    "https://example.fief.dev/api/token",  
    scopes={"openid": "openid", "offline_access": "offline_access"},
    auto_error=False  # This is important
 )
```

I'll fix the docs to reflect this! Thank you for reporting 🙏
